### ISSUE TITLE
feature: preview colors in autocompletion popup

### ISSUE THREAD

**Issue by danielweck** [tw-in-js/typescript-plugin#10]
As implemented by:

https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss

<img width="1040" alt="autocomplete" src="https://user-images.githubusercontent.com/625201/111222711-19f54f00-85d4-11eb-8378-4481a3ef4b98.png">

**Comment by danielweck** [comment]
I suspect this has something to do with it:
https://github.com/tailwindlabs/tailwindcss-intellisense/blob/master/packages/tailwindcss-intellisense/src/lib/registerColorDecorator.ts

**Comment by sastan** [comment]
That should be fixed with the new 0.2.0 release.

**Comment by danielweck** [comment]
Awesome :)
Thank you for your hard work and quick turnaround! This makes a difference to the adoption of Twind (I am not a big fan of Tailwind's default build/integration approach, and I love the flexibility that Twind brings (i.e. hybrid CSS-in-JS + declarative utility classes))

Just a question (just in case this is a bug, not a feature): the colour indicator only appears when the popup menu item is keyboard-navigated with the arrow keys (fine by me, but just wondering if this is intentional). See screenshot below:

<img width="1014" alt="Screenshot 2021-03-16 at 06 32 53" src="https://user-images.githubusercontent.com/625201/111265762-82b6e880-8621-11eb-9788-d7e31c282e53.png">

**Comment by danielweck** [comment]
PS: I love the "hover" feature which reveals the raw CSS (just like the Tailwind VSCode plugin). Very useful for those like me who actually know/like CSS syntax, but who prefer to write styling code quicker by using the opinionated terse aliases that Tailwind provides.

**Comment by sastan** [comment]
> Just a question (just in case this is a bug, not a feature): the colour indicator only appears when the popup menu item is keyboard-navigated with the arrow keys (fine by me, but just wondering if this is intentional).

The plugin provides all the informations. I experienced the same. Maybe there is a way to tell VS Code to render those immediately.
