### ISSUE TITLE
autocompletion fails with "translate-x/y-" (but works with "translate-")

### ISSUE THREAD

**Issue by danielweck** [tw-in-js/typescript-plugin#12]
As discussed here:
https://github.com/tw-in-js/typescript-plugin/issues/8
...the hover preview of raw CSS, and the error highlighting both work fine. It is just the completion that fails.

`translate-14` autocompletes fine (after the dash `-`), but `translate-x-14` fails.

I am filing this here as I suspect the issue is in the VSCode extension, rather than in Twind core (i.e. where the transform tokens are defined).

**Comment by sastan** [comment]
Should be fixed with twind@0.16.2

**Comment by danielweck** [comment]
Great thanks :)

**Comment by sastan** [comment]
And there is a new version this plugin with better autocomplete, context aware hover (depending on active grouping) and warnings for unknown variants.
