### ISSUE TITLE
Support for Tailwind v1 completions

### ISSUE THREAD

**Issue by IgnusG** [tw-in-js/typescript-plugin#20]
I see that the `...Plugins` that were mainly used for plugin completions in twind 0.16 have been removed in v1. Currently there does not seem to be a replacement anywhere. I remember reading somewhere in ToDo's (maybe I'm dumb but I cannot find them anymore 😅) that this shall be extracted into `@twind/completions` and I guess twind's `typescript-plugin` will then use those. 

Are these completions planned for the v1 release as well? 

> I  have trouble remembering all the tailwind classes by heart so this feature would be great to improve the speed at which one can use twind to quickly prototype projects.

**Comment by sastan** [comment]
I move the TODOs to https://github.com/tw-in-js/twind/blob/next/ROADMAP.md

Currently, there are no completions. You can try the tailwindcss v3 extensions. I plan to create a `@twind/completions` and update the VS Code extension. But that will take some time. I want to create a website and some framework integrations first.

**Comment by xlboy** [comment]
> I move the TODOs to https://github.com/tw-in-js/twind/blob/next/ROADMAP.md
> 
> Currently, there are no completions. You can try the tailwindcss v3 extensions. I plan to create a `@twind/completions` and update the VS Code extension. But that will take some time. I want to create a website and some framework integrations first.

Can you share the plans related to @twind/completions? I would be happy to contribute.
