### ISSUE TITLE
Support for `tw` prop from `@twind/jsx-preprocessors`

### ISSUE THREAD

**Issue by itsMapleLeaf** [tw-in-js/typescript-plugin#3]
The autocomplete for tw\`\` works great, but it'd also be nice to get the same when using the macro `tw` prop. I wouldn't mind implementing this myself, but I haven't touched typescript plugins in a while 😅 A pointer in the right direction on this would be appreciated

**Comment by sastan** [comment]
I honestly don't know. This is my first attempt on a typescript plugin.

**Comment by sastan** [comment]
Will definitly support this.

**Comment by sastan** [comment]
This should be fixed with 0.3.0.

@itsMapleLeaf Could you verify that your cases are handled?

**Comment by itsMapleLeaf** [comment]
I can verify it later, thanks 😊

**Comment by itsMapleLeaf** [comment]
Works like a charm! I'll be closing this then
