### ISSUE TITLE
Autocomplete "eats" the text after the completed entry

### ISSUE THREAD

**Issue by itsMapleLeaf** [tw-in-js/typescript-plugin#4]
![1mAA1isznX](https://user-images.githubusercontent.com/19603573/106703889-c3e2c400-65b0-11eb-9d9f-1abb4c72af3d.gif)

I'm currently getting around this by adding a space at the end, but... yeah 😅 

I'm not sure if this is a plugin problem or an editor problem. If it's an editor problem, some recommended config in the docs would probably help

**Comment by sastan** [comment]
This plugin needs some love. I don't know when I'll get to it.

**Comment by itsMapleLeaf** [comment]
Ah, I did figure out the issue, though. In my VSCode editor settings, I apparently had `"editor.suggest.insertMode": "replace",`, and changing it to `"insert"` resolved this. I don't remember when or why I changed that 😆 

If this could be configured on a plugin-specific basis, that might be better though

**Comment by itsMapleLeaf** [comment]
Yeah, I think we're good to close this
