### ISSUE TITLE
User config support

### ISSUE THREAD

**Issue by itsMapleLeaf** [tw-in-js/typescript-plugin#6]
Add the ability to read config from `[src/]twind.config.[ts/js]`. I'll see if I can make this work myself 😄

**Comment by sastan** [comment]
Definitly! I have something like https://github.com/tw-in-js/twind-cli/blob/main/src/run.ts#L20 integrated. I hope to publish my work soon.

**Comment by sastan** [comment]
Suppport for `twind.config.[ts/js]` in the project folder is includes in the new release. Will add `{src,public}/twind.config.[ts/js]` in the next days.

**Comment by sastan** [comment]
This should be fixed with 0.2.2: `[config/,src/,public/]twind.config.{ts,js,cjs,mjs}`

**Comment by danielweck** [comment]
Hello, can this issue now be closed? :)
