### ISSUE TITLE
Great plugin for Visual Studio Code / "intellisense"! ... here's my tip to use this efficiently with Twind prerender / server shim (i.e. plain class attribute values)

### ISSUE THREAD

**Issue by danielweck** [tw-in-js/typescript-plugin#7]
As a Tailwind beginner, I find autocompletion essential. So, thank you for this plugin! :)

In my [preact-wmr](https://github.com/preactjs/wmr/) projects I like to write JSX/TSX code like this:

```jsx
<h1 class={tw`text-4xl font-extrabold bg-red-200`}>My header</h1>
```

...which works absolutely fine with Preact WMR's "prerender" (static Server Side Rendering):

* https://github.com/tw-in-js/example-wmr
* https://github.com/tw-in-js/twind/tree/main/src/server
* https://twind.dev/docs/handbook/advanced/ssr.html

However, the `{tw'...'}` calls remain in the client-side hydration code that the server generates as part of the pre-rendered HTML documents. This makes total sense, but I wanted to avoid unnecessary potentially-costly operations in the web browser runtime. Especially as Twind's injected `<style id="__twind">` stylesheet is already present in the pre-rendered HTML, so calling`{tw'...'}` to hydrate the exact same CSS object model is a waste of resources.

An easy way to fix this is to use plain `class` values instead:

```html
<h1 class="text-4xl font-extrabold bg-red-200">My header</h1>
```

...along with client-side shim code that runs only at development time (i.e. not at production / pre-rendering time):

* https://github.com/tw-in-js/twind/tree/main/src/shim

...unfortunately the plain `class` attribute syntax isn't supported by `@twind/typescript-plugin`.

Thankfully, a hybrid solution can easily be implemented, using a Preact WMR plugin (i.e. Rollup-like hooks) at build/prod time that statically replaces `{tw'...'}` calls with their plain counterparts, **after** WMR's pre-render pass but **before** Twind's own NodeJS server-side parsing.

One obvious problem with this approach is that it isn't compatible with interpolated values inside the `tw` template string function (because the dynamic values resolve correctly on the server side based on static defaults, but wouldn't necessarily represent the dynamic values computed in the web browser runtime / during hydration). So it is critical that such interpolated / dynamic `{tw'...'}` calls are ignored by the build/prerender plugin so they remain completely dynamic at hydration time.

This method works in my [`clsx`](https://github.com/lukeed/clsx) (`classnames` alternative) calls as well. For example (note: the `isActive` and `props.loading` booleans have a default value during static SSR, and a dynamic value after hydration):

```jsx
<a
  href={props.href}
  class={clsx(
    tw`focus:bg-blue-200`,
    tw`ml-4 p-4 bg-red-50 rounded-lg border-4 border-red-400 hover:bg-red-100 cursor-pointer`,
    { 'underline font-bold': isActive },
    { 'override:(cursor-wait italic)': isActive && props.loading },
  )}
>
  {props.label}
</a>
```

Example of interpolated string skipped by the plugin:

```
const x = 'font-extrabold';
export const myComponent = () => <h1 class={tw`text-4xl ${x} bg-red-200`}>My heading</h1>
```

Here's my quick and dirty WMR plugin config:

(as you can see, the regular expressions are trivial, and I am sure could easily be improved to work with edge cases ... also note that there are internal / built-in plugins in Preact WMR that parse HTML / walk the DOM tree to perform some operations, but I decided to use regular expressions as this works just fine in my usage scenario, and it's fast)

`wmr.config.mjs`

=>

```js
const TWIND_REGEXP1 = /{tw`([\sa-zA-Z0-9:\-()@.,/!]+)`}/gm;
const TWIND_REGEXP2 = /tw`([\sa-zA-Z0-9:\-()@.,/!]+)`/gm;

/** @param {import('wmr').Options} config */
export default async function (config) {

	/**
	 * @type {import('rollup').Plugin}
	 */
	const twPlugin = {
		name: 'Twind',
		transform(code, id) {
			if (!/\.[tj]sx?$/.test(id)) return;
			if (id[0] === '\0' || id[0] === '\b') return;
const func = (_match, $1) => {
    const classes = $1.replace(/\s\s+/g, ' ');
    return `"${classes}"`;
};
			if (config.mode === 'build') {
				if (TWIND_REGEXP1.test(code)) {
					console.log('>>> Tailwind TW-in-JS Twind transform 1', id);
					code = code.replace(TWIND_REGEXP1, func);
				}
				if (TWIND_REGEXP2.test(code)) {
					console.log('>>> Tailwind TW-in-JS Twind transform 2', id);
					code = code.replace(TWIND_REGEXP2, func);
				}
				return { code, map: null };
			}

			return null;
		},
	};
	config.plugins.push(twPlugin);
}
```

One final note: in my Preact WMR project I make use of the `tw()` function (with `css()` and `apply()`) to bring additional configuration into the Twind-generated stylesheet, at hydration time (i.e. "on top" of the statically-generated pre-rendered `<style id="__twind">` stylesheet). Something like that:

```js
const styles = css({
    ':global': {
        // stylelint-disable-next-line property-no-unknown
        ':root body': apply('bg-yellow-200'),
        // stylelint-disable-next-line property-no-unknown
        '*::selection': apply('bg-yellow-400 text-red-900'),
        // stylelint-disable-next-line property-no-unknown
        'input::selection': apply('bg-pink-200 text-pink-900'),
    },
});
tw(styles);
```

This works absolutely fine, especially as the styles defined here are usually for "progressive" enhancement, i.e. not critical to first render / first interaction (although the execution is so fast it is barely noticeable from the user perspective ... I have to add a generous `setTimeout()` in my code to make sure all is running according to plan!). The only issue with this technique is that it doesn't play well with Hot Module Reload / Fast Refresh (Prefresh, in the case of Preact) ... but that's a totally different topic :)

I don't have time to contribute a PR for a usage "recipe" in https://github.com/tw-in-js/twind , but feel free to close this issue and to implement the technique yourself in https://github.com/tw-in-js/example-wmr (the more I think about it: I should probably create a `twind-wmr` repository / Gist myself to showcase what's possible ... I just don't have the bandwidth at the moment)

Thanks for your open-source libs and documentation! Keep up the good work.

**Comment by sastan** [comment]
Whoa! Thanks for that example, your use case, and all the infos. Your rollup plugin seems to be a very good idea for all those static styles! @itsMapleLeaf manages the [twind-jsx-preprocessor](https://github.com/tw-in-js/twind-jsx-preprocessor)  repo. Maybe he can turn that into something re-useable. I put it on my (long) list of tasks for twind.

I'm currently working on several packages that may help you a lot. I hope to get them released by the weekend.

1. This plugin will get an upgrade to auto detect the autocompletion values. I look into supporting the `class`/`className` attribute as well.
2. I have a @twind/preact integration plugin in the pipeline that will support `tw`, `css`, and `class`/`className`(for the shim experience without the shim) props and merge those into the `className` attribute at runtime/prerender:

  ```html
  <div tw="text-xl font-medium text-black" className="title">{title}</div>  
  ```

  ```html
  <div class="text-xl font-medium text-black title">{title}</div>  
  ```

3. And an @twind/wmr package that would simplify the setup:

  ```js
  import withTwind from '@twind/wmr'
  import twindConfig from './twind.config.js'
  
  const { hydrate, prerender } = withTwind(twindConfig, (data) => <App {...data} />)
  
  hydrate(<App />)
  
  export { prerender }
  ```

**Comment by danielweck** [comment]
Hi! :)
I improved the regexp slightly:
```
const TWIND_REGEXP1 = /{tw`([ a-zA-Z0-9:\-()@\t]+)`}/gm;
const TWIND_REGEXP2 = /tw`([ a-zA-Z0-9:\-()@\t]+)`/gm;
```

**Comment by danielweck** [comment]
By the way: there are internal / built-in plugins in Preact WMR that parse HTML / walk the DOM tree to perform some operations, but I decided to use regular expressions as this works just fine in my usage scenario, and it's fast.

**Comment by danielweck** [comment]
>     1. I look into supporting the `class`/`className` attribute as well.

That would be sweet, as this would negate the need for my hacked-up Preact WMR pre-rendering plugin that transforms the `<div class={tw'font-bold'}>` notation to `<div class="font-bold">`. Conversely, this would add the runtime cost of the Twind "shim" at development time (i.e. the "observer" instance), which is probably a little more expensive than just invoking the `tw` function directly in-situ. Minor problem though :)

**Comment by sastan** [comment]
> That would be sweet, as this would negate the need for my hacked-up Preact WMR pre-rendering plugin that transforms the `<div class={tw'font-bold'}>` notation to `<div class="font-bold">`. Conversely, this would add the runtime cost of the Twind "shim" at development time (i.e. the "observer" instance), which is probably a little more expensive than just invoking the `tw` function directly in-situ. Minor problem though :)

Not quite. The preact plugin [hooks](https://preactjs.com/guide/v10/options) into the vnode creation and transforms the mentioned properties using the tw function into classes which are then appended to the className property.

1. twind/shim is not used and therefore not observer – although I doubt that MutationObserver are that expensive, but who knows
2. Your plugin would still be needed but could transform the tw property and add it to the class property.

**Comment by sastan** [comment]
> Hi! :)
> I improved the regexp slightly:
> 
> ```
> const TWIND_REGEXP1 = /{tw`([ a-zA-Z0-9:\-()@\t]+)`}/gm;
> const TWIND_REGEXP2 = /tw`([ a-zA-Z0-9:\-()@\t]+)`/gm;
> ```

The class names may be multline and can contain the following chars as well: `.,/!`

**Comment by danielweck** [comment]
> The class names may be multline and can contain the following chars as well: `.,/!`

Thanks!

Re. multiline: that's why I used `/gm`.

This seems to work fine (copy verbatim in shell):

```
node -e 'console.log(/{tw`([ a-zA-Z0-9:\-()@\t.,/!]+)`}/gm.test("{tw`ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-()@ :	.,/!\
`}"))'
```

**Comment by danielweck** [comment]
Well, this isn't working well after all :D
The transformation of the JSX/TSX "erases" the `tw'...'` registrations, so obviously the server shim (HTML parser) is needed to execute `tw` on the class attributes (I was mistaken into thinking that the transform was happening AFTER the Preact WMR render, i.e. after all `tw''` registrations!).
Anyway, it was good to explore the problem space, I will keep an eye on your developments :)
Thanks!
