### ISSUE TITLE
autocomplete fails after group expression

### ISSUE THREAD

**Issue by danielweck** [tw-in-js/typescript-plugin#9]
Works fine:

<img width="1014" alt="Screenshot 2021-03-15 at 21 08 29" src="https://user-images.githubusercontent.com/625201/111221789-de0dba00-85d2-11eb-9daa-c1780d4e7f69.png">

and this too:

<img width="1014" alt="Screenshot 2021-03-15 at 21 08 34" src="https://user-images.githubusercontent.com/625201/111221805-e2d26e00-85d2-11eb-9088-44bf25e5988c.png">

**Comment by danielweck** [comment]
..but this fails:

<img width="1014" alt="Screenshot 2021-03-15 at 21 08 52" src="https://user-images.githubusercontent.com/625201/111221837-ef56c680-85d2-11eb-968e-a15e03e43a46.png">

...although the group located before works fine:

<img width="1014" alt="Screenshot 2021-03-15 at 21 08 59" src="https://user-images.githubusercontent.com/625201/111221873-fb428880-85d2-11eb-84fa-afdde3a68b40.png">

**Comment by danielweck** [comment]
I suspect the culprit is somewhere in there?

https://github.com/tw-in-js/typescript-plugin/blob/main/src/parse.ts

**Comment by sastan** [comment]
I have just release a new version (0.2.0). Could try that one please.

**Comment by danielweck** [comment]
Fixed, well done, and thank you very much! :)
